name: MakeMeAdmin
author: Xenophilicy
version: 4.0.0
main: MakeMeAdmin\Main
api: [3.0.0, 3.5.3, 3.5.4, 3.5.5]
commands:
  mma:
    description: Manage Your Rank
    permission: makemeadmin.use.ui
  mmadmin:
    description: Manage Your Rank
    permission: makemeadmin.use.ui
  makemeadmin:
    description: Get Info On MakeMeAdmin Plugin
    permission: makemeadmin.use.about
permissions:
  makemeadmin.use:
    default: op
    children:
        makemeadmin.use.1:
          children:
            makemeadmin.use.ui:
            default: op
        makemeadmin.use.2:
          children:
            makemeadmin.use.ui:
            default: op
        makemeadmin.use.3:
          children:
            makemeadmin.use.ui:
            default: op
        makemeadmin.use.4:
          children:
            makemeadmin.use.ui:
            default: op
        makemeadmin.use.5:
          children:
            makemeadmin.use.ui:
            default: op
        makemeadmin.use.about:
          default: op
