name: MakeMeAdmin
author: Xenophilicy
version: 2.0.0
main: MakeMeAdmin\Main
api: [3.0.0]
commands:
  mma:
    description: Manage Your Rank
    permission: makemeadmin.use.ui
  mmadmin:
    description: Manage Your Rank
    permission: makemeadmin.use.ui
  makemeadmin:
    description: Get Info On MakeMeAdmin Plugin
    permission: makemeadmin.use.about
permissions:
  makemeadmin.use:
    default: true
    children:
        makemeadmin.use.1:
          children:
            makemeadmin.use.ui:
            default: true
        makemeadmin.use.2:
          children:
            makemeadmin.use.ui:
            default: true
        makemeadmin.use.3:
          children:
            makemeadmin.use.ui:
            default: true
        makemeadmin.use.4:
          children:
            makemeadmin.use.ui:
            default: true
        makemeadmin.use.5:
          children:
            makemeadmin.use.ui:
            default: true
        makemeadmin.use.about:
          default: true
